name: appmetrica_sdk
description: A Flutter plugin for Yandex AppMetrica SDK, a marketing platform for
  app install attribution, app analytics, and push campaigns.
version: 0.1.0
homepage: https://github.com/EMALLStudio/appmetrica_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.emallstudio.appmetrica_sdk
        pluginClass: AppMetricaSdkPlugin
      ios:
        pluginClass: AppmetricaSdkPlugin